package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksAftersale;
import com.angeleo.sks.db.pojo.SksAftersaleExample;
import org.apache.ibatis.annotations.Param;


public interface SksAftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    long countByExample(SksAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    int deleteByExample(SksAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    int insert(SksAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    int insertSelective(SksAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    SksAftersale selectOneByExample(SksAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    SksAftersale selectOneByExampleSelective(@Param("example") SksAftersaleExample example, @Param("selective") SksAftersale.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    List<SksAftersale> selectByExampleSelective(@Param("example") SksAftersaleExample example, @Param("selective") SksAftersale.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    List<SksAftersale> selectByExample(SksAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    SksAftersale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksAftersale.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    SksAftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    SksAftersale selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksAftersale record, @Param("example") SksAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksAftersale record, @Param("example") SksAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}