package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksAd;
import com.angeleo.sks.db.pojo.SksAdExample;
import org.apache.ibatis.annotations.Param;


public interface SksAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    long countByExample(SksAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    int deleteByExample(SksAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    int insert(SksAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    int insertSelective(SksAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    SksAd selectOneByExample(SksAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    SksAd selectOneByExampleSelective(@Param("example") SksAdExample example, @Param("selective") SksAd.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    List<SksAd> selectByExampleSelective(@Param("example") SksAdExample example, @Param("selective") SksAd.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    List<SksAd> selectByExample(SksAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    SksAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksAd.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    SksAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    SksAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksAd record, @Param("example") SksAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksAd record, @Param("example") SksAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_ad
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}