package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksAddress;
import com.angeleo.sks.db.pojo.SksAddressExample;
import org.apache.ibatis.annotations.Param;


public interface SksAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    long countByExample(SksAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    int deleteByExample(SksAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    int insert(SksAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    int insertSelective(SksAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    SksAddress selectOneByExample(SksAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    SksAddress selectOneByExampleSelective(@Param("example") SksAddressExample example, @Param("selective") SksAddress.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    List<SksAddress> selectByExampleSelective(@Param("example") SksAddressExample example, @Param("selective") SksAddress.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    List<SksAddress> selectByExample(SksAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    SksAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksAddress.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    SksAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    SksAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksAddress record, @Param("example") SksAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksAddress record, @Param("example") SksAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_address
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}