package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksBrand;
import com.angeleo.sks.db.pojo.SksBrandExample;
import org.apache.ibatis.annotations.Param;


public interface SksBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    long countByExample(SksBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    int deleteByExample(SksBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    int insert(SksBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    int insertSelective(SksBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    SksBrand selectOneByExample(SksBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    SksBrand selectOneByExampleSelective(@Param("example") SksBrandExample example, @Param("selective") SksBrand.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    List<SksBrand> selectByExampleSelective(@Param("example") SksBrandExample example, @Param("selective") SksBrand.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    List<SksBrand> selectByExample(SksBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    SksBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksBrand.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    SksBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    SksBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksBrand record, @Param("example") SksBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksBrand record, @Param("example") SksBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_brand
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}