package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksCategory;
import com.angeleo.sks.db.pojo.SksCategoryExample;
import org.apache.ibatis.annotations.Param;


public interface SksCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    long countByExample(SksCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    int deleteByExample(SksCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    int insert(SksCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    int insertSelective(SksCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    SksCategory selectOneByExample(SksCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    SksCategory selectOneByExampleSelective(@Param("example") SksCategoryExample example, @Param("selective") SksCategory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    List<SksCategory> selectByExampleSelective(@Param("example") SksCategoryExample example, @Param("selective") SksCategory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    List<SksCategory> selectByExample(SksCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    SksCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksCategory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    SksCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    SksCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksCategory record, @Param("example") SksCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksCategory record, @Param("example") SksCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_category
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}