package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksCollect;
import com.angeleo.sks.db.pojo.SksCollectExample;
import org.apache.ibatis.annotations.Param;


public interface SksCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    long countByExample(SksCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    int deleteByExample(SksCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    int insert(SksCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    int insertSelective(SksCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    SksCollect selectOneByExample(SksCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    SksCollect selectOneByExampleSelective(@Param("example") SksCollectExample example, @Param("selective") SksCollect.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    List<SksCollect> selectByExampleSelective(@Param("example") SksCollectExample example, @Param("selective") SksCollect.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    List<SksCollect> selectByExample(SksCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    SksCollect selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksCollect.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    SksCollect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    SksCollect selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksCollect record, @Param("example") SksCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksCollect record, @Param("example") SksCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_collect
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}