package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksCart;
import com.angeleo.sks.db.pojo.SksCartExample;
import org.apache.ibatis.annotations.Param;


public interface SksCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    long countByExample(SksCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    int deleteByExample(SksCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    int insert(SksCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    int insertSelective(SksCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    SksCart selectOneByExample(SksCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    SksCart selectOneByExampleSelective(@Param("example") SksCartExample example, @Param("selective") SksCart.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    List<SksCart> selectByExampleSelective(@Param("example") SksCartExample example, @Param("selective") SksCart.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    List<SksCart> selectByExample(SksCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    SksCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksCart.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    SksCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    SksCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksCart record, @Param("example") SksCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksCart record, @Param("example") SksCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_cart
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}