package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksComment;
import com.angeleo.sks.db.pojo.SksCommentExample;
import org.apache.ibatis.annotations.Param;


public interface SksCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    long countByExample(SksCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    int deleteByExample(SksCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    int insert(SksComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    int insertSelective(SksComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    SksComment selectOneByExample(SksCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    SksComment selectOneByExampleSelective(@Param("example") SksCommentExample example, @Param("selective") SksComment.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    List<SksComment> selectByExampleSelective(@Param("example") SksCommentExample example, @Param("selective") SksComment.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    List<SksComment> selectByExample(SksCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    SksComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksComment.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    SksComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    SksComment selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksComment record, @Param("example") SksCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksComment record, @Param("example") SksCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_comment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}