package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksCouponUser;
import com.angeleo.sks.db.pojo.SksCouponUserExample;
import org.apache.ibatis.annotations.Param;

public interface SksCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(SksCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(SksCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    int insert(SksCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(SksCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    SksCouponUser selectOneByExample(SksCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    SksCouponUser selectOneByExampleSelective(@Param("example") SksCouponUserExample example, @Param("selective") SksCouponUser.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    List<SksCouponUser> selectByExampleSelective(@Param("example") SksCouponUserExample example, @Param("selective") SksCouponUser.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    List<SksCouponUser> selectByExample(SksCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    SksCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksCouponUser.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    SksCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    SksCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksCouponUser record, @Param("example") SksCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksCouponUser record, @Param("example") SksCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}