package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksCoupon;
import com.angeleo.sks.db.pojo.SksCouponExample;
import org.apache.ibatis.annotations.Param;


public interface SksCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    long countByExample(SksCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(SksCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    int insert(SksCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    int insertSelective(SksCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    SksCoupon selectOneByExample(SksCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    SksCoupon selectOneByExampleSelective(@Param("example") SksCouponExample example, @Param("selective") SksCoupon.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    List<SksCoupon> selectByExampleSelective(@Param("example") SksCouponExample example, @Param("selective") SksCoupon.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    List<SksCoupon> selectByExample(SksCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    SksCoupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksCoupon.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    SksCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    SksCoupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksCoupon record, @Param("example") SksCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksCoupon record, @Param("example") SksCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_coupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}