package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksFeedback;
import com.angeleo.sks.db.pojo.SksFeedbackExample;
import org.apache.ibatis.annotations.Param;


public interface SksFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    long countByExample(SksFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(SksFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    int insert(SksFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    int insertSelective(SksFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    SksFeedback selectOneByExample(SksFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    SksFeedback selectOneByExampleSelective(@Param("example") SksFeedbackExample example, @Param("selective") SksFeedback.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    List<SksFeedback> selectByExampleSelective(@Param("example") SksFeedbackExample example, @Param("selective") SksFeedback.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    List<SksFeedback> selectByExample(SksFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    SksFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksFeedback.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    SksFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    SksFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksFeedback record, @Param("example") SksFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksFeedback record, @Param("example") SksFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_feedback
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}