package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksGoodsProduct;
import com.angeleo.sks.db.pojo.SksGoodsProductExample;
import org.apache.ibatis.annotations.Param;


public interface SksGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    long countByExample(SksGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(SksGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    int insert(SksGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(SksGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    SksGoodsProduct selectOneByExample(SksGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    SksGoodsProduct selectOneByExampleSelective(@Param("example") SksGoodsProductExample example, @Param("selective") SksGoodsProduct.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    List<SksGoodsProduct> selectByExampleSelective(@Param("example") SksGoodsProductExample example, @Param("selective") SksGoodsProduct.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    List<SksGoodsProduct> selectByExample(SksGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    SksGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksGoodsProduct.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    SksGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    SksGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksGoodsProduct record, @Param("example") SksGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksGoodsProduct record, @Param("example") SksGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_product
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}