package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksGoodsAttribute;
import com.angeleo.sks.db.pojo.SksGoodsAttributeExample;
import org.apache.ibatis.annotations.Param;

public interface SksGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(SksGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(SksGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    int insert(SksGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(SksGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    SksGoodsAttribute selectOneByExample(SksGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    SksGoodsAttribute selectOneByExampleSelective(@Param("example") SksGoodsAttributeExample example, @Param("selective") SksGoodsAttribute.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    List<SksGoodsAttribute> selectByExampleSelective(@Param("example") SksGoodsAttributeExample example, @Param("selective") SksGoodsAttribute.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    List<SksGoodsAttribute> selectByExample(SksGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    SksGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksGoodsAttribute.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    SksGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    SksGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksGoodsAttribute record, @Param("example") SksGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksGoodsAttribute record, @Param("example") SksGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_attribute
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}