package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksGroupon;
import com.angeleo.sks.db.pojo.SksGrouponExample;
import org.apache.ibatis.annotations.Param;


public interface SksGrouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    long countByExample(SksGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    int deleteByExample(SksGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    int insert(SksGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    int insertSelective(SksGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    SksGroupon selectOneByExample(SksGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    SksGroupon selectOneByExampleSelective(@Param("example") SksGrouponExample example, @Param("selective") SksGroupon.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    List<SksGroupon> selectByExampleSelective(@Param("example") SksGrouponExample example, @Param("selective") SksGroupon.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    List<SksGroupon> selectByExample(SksGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    SksGroupon selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksGroupon.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    SksGroupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    SksGroupon selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksGroupon record, @Param("example") SksGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksGroupon record, @Param("example") SksGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksGroupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksGrouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_groupon
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}