package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksGoodsSpecification;
import com.angeleo.sks.db.pojo.SksGoodsSpecificationExample;
import org.apache.ibatis.annotations.Param;

public interface SksGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(SksGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(SksGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    int insert(SksGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(SksGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    SksGoodsSpecification selectOneByExample(SksGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    SksGoodsSpecification selectOneByExampleSelective(@Param("example") SksGoodsSpecificationExample example, @Param("selective") SksGoodsSpecification.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    List<SksGoodsSpecification> selectByExampleSelective(@Param("example") SksGoodsSpecificationExample example, @Param("selective") SksGoodsSpecification.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    List<SksGoodsSpecification> selectByExample(SksGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    SksGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksGoodsSpecification.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    SksGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    SksGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksGoodsSpecification record, @Param("example") SksGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksGoodsSpecification record, @Param("example") SksGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_goods_specification
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}