package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksKeyword;
import com.angeleo.sks.db.pojo.SksKeywordExample;
import org.apache.ibatis.annotations.Param;
public interface SksKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    long countByExample(SksKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(SksKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    int insert(SksKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    int insertSelective(SksKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    SksKeyword selectOneByExample(SksKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    SksKeyword selectOneByExampleSelective(@Param("example") SksKeywordExample example, @Param("selective") SksKeyword.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    List<SksKeyword> selectByExampleSelective(@Param("example") SksKeywordExample example, @Param("selective") SksKeyword.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    List<SksKeyword> selectByExample(SksKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    SksKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksKeyword.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    SksKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    SksKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksKeyword record, @Param("example") SksKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksKeyword record, @Param("example") SksKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}