package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksNoticeAdmin;
import com.angeleo.sks.db.pojo.SksNoticeAdminExample;
import org.apache.ibatis.annotations.Param;


public interface SksNoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    long countByExample(SksNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    int deleteByExample(SksNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    int insert(SksNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    int insertSelective(SksNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    SksNoticeAdmin selectOneByExample(SksNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    SksNoticeAdmin selectOneByExampleSelective(@Param("example") SksNoticeAdminExample example, @Param("selective") SksNoticeAdmin.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    List<SksNoticeAdmin> selectByExampleSelective(@Param("example") SksNoticeAdminExample example, @Param("selective") SksNoticeAdmin.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    List<SksNoticeAdmin> selectByExample(SksNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    SksNoticeAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksNoticeAdmin.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    SksNoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    SksNoticeAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksNoticeAdmin record, @Param("example") SksNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksNoticeAdmin record, @Param("example") SksNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}