package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksOrder;
import com.angeleo.sks.db.pojo.SksOrderExample;
import org.apache.ibatis.annotations.Param;

public interface SksOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    long countByExample(SksOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    int deleteByExample(SksOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    int insert(SksOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    int insertSelective(SksOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    SksOrder selectOneByExample(SksOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    SksOrder selectOneByExampleSelective(@Param("example") SksOrderExample example, @Param("selective") SksOrder.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    List<SksOrder> selectByExampleSelective(@Param("example") SksOrderExample example, @Param("selective") SksOrder.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    List<SksOrder> selectByExample(SksOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    SksOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksOrder.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    SksOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    SksOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksOrder record, @Param("example") SksOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksOrder record, @Param("example") SksOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}