package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksPermission;
import com.angeleo.sks.db.pojo.SksPermissionExample;
import org.apache.ibatis.annotations.Param;

public interface SksPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    long countByExample(SksPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    int deleteByExample(SksPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    int insert(SksPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    int insertSelective(SksPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    SksPermission selectOneByExample(SksPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    SksPermission selectOneByExampleSelective(@Param("example") SksPermissionExample example, @Param("selective") SksPermission.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    List<SksPermission> selectByExampleSelective(@Param("example") SksPermissionExample example, @Param("selective") SksPermission.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    List<SksPermission> selectByExample(SksPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    SksPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksPermission.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    SksPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    SksPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksPermission record, @Param("example") SksPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksPermission record, @Param("example") SksPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}