package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksRole;
import com.angeleo.sks.db.pojo.SksRoleExample;
import org.apache.ibatis.annotations.Param;

public interface SksRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    long countByExample(SksRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    int deleteByExample(SksRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    int insert(SksRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    int insertSelective(SksRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    SksRole selectOneByExample(SksRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    SksRole selectOneByExampleSelective(@Param("example") SksRoleExample example, @Param("selective") SksRole.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    List<SksRole> selectByExampleSelective(@Param("example") SksRoleExample example, @Param("selective") SksRole.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    List<SksRole> selectByExample(SksRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    SksRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksRole.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    SksRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    SksRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksRole record, @Param("example") SksRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksRole record, @Param("example") SksRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}