package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksRegion;
import com.angeleo.sks.db.pojo.SksRegionExample;
import org.apache.ibatis.annotations.Param;

public interface SksRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    long countByExample(SksRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    int deleteByExample(SksRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    int insert(SksRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    int insertSelective(SksRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    SksRegion selectOneByExample(SksRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    SksRegion selectOneByExampleSelective(@Param("example") SksRegionExample example, @Param("selective") SksRegion.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    List<SksRegion> selectByExampleSelective(@Param("example") SksRegionExample example, @Param("selective") SksRegion.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    List<SksRegion> selectByExample(SksRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    SksRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksRegion.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    SksRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksRegion record, @Param("example") SksRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksRegion record, @Param("example") SksRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksRegion record);
}