package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksSnapUpRules;
import com.angeleo.sks.db.pojo.SksSnapUpRulesExample;
import org.apache.ibatis.annotations.Param;

public interface SksSnapUpRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    long countByExample(SksSnapUpRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    int deleteByExample(SksSnapUpRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    int insert(SksSnapUpRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    int insertSelective(SksSnapUpRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    SksSnapUpRules selectOneByExample(SksSnapUpRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    SksSnapUpRules selectOneByExampleSelective(@Param("example") SksSnapUpRulesExample example, @Param("selective") SksSnapUpRules.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    List<SksSnapUpRules> selectByExampleSelective(@Param("example") SksSnapUpRulesExample example, @Param("selective") SksSnapUpRules.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    List<SksSnapUpRules> selectByExample(SksSnapUpRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    SksSnapUpRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksSnapUpRules.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    SksSnapUpRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    SksSnapUpRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksSnapUpRules record, @Param("example") SksSnapUpRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksSnapUpRules record, @Param("example") SksSnapUpRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksSnapUpRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksSnapUpRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksSnapUpRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup_rules
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}