package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksStorage;
import com.angeleo.sks.db.pojo.SksStorageExample;
import org.apache.ibatis.annotations.Param;

public interface SksStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    long countByExample(SksStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    int deleteByExample(SksStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    int insert(SksStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    int insertSelective(SksStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    SksStorage selectOneByExample(SksStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    SksStorage selectOneByExampleSelective(@Param("example") SksStorageExample example, @Param("selective") SksStorage.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    List<SksStorage> selectByExampleSelective(@Param("example") SksStorageExample example, @Param("selective") SksStorage.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    List<SksStorage> selectByExample(SksStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    SksStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksStorage.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    SksStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    SksStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksStorage record, @Param("example") SksStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksStorage record, @Param("example") SksStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}