package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksSnapUp;
import com.angeleo.sks.db.pojo.SksSnapUpExample;
import org.apache.ibatis.annotations.Param;


/**
 * @author leo
 */
public interface SksSnapUpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    long countByExample(SksSnapUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    int deleteByExample(SksSnapUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    int insert(SksSnapUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    int insertSelective(SksSnapUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    SksSnapUp selectOneByExample(SksSnapUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    SksSnapUp selectOneByExampleSelective(@Param("example") SksSnapUpExample example, @Param("selective") SksSnapUp.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    List<SksSnapUp> selectByExampleSelective(@Param("example") SksSnapUpExample example, @Param("selective") SksSnapUp.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    List<SksSnapUp> selectByExample(SksSnapUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    SksSnapUp selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksSnapUp.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    SksSnapUp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    SksSnapUp selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksSnapUp record, @Param("example") SksSnapUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksSnapUp record, @Param("example") SksSnapUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksSnapUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksSnapUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksSnapUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_snapup
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}