package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksSystem;
import com.angeleo.sks.db.pojo.SksSystemExample;
import org.apache.ibatis.annotations.Param;

public interface SksSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    long countByExample(SksSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    int deleteByExample(SksSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    int insert(SksSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    int insertSelective(SksSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    SksSystem selectOneByExample(SksSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    SksSystem selectOneByExampleSelective(@Param("example") SksSystemExample example, @Param("selective") SksSystem.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    List<SksSystem> selectByExampleSelective(@Param("example") SksSystemExample example, @Param("selective") SksSystem.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    List<SksSystem> selectByExample(SksSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    SksSystem selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksSystem.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    SksSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    SksSystem selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksSystem record, @Param("example") SksSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksSystem record, @Param("example") SksSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_system
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}