package com.angeleo.sks.db.mapper;

import java.util.List;

import com.angeleo.sks.db.pojo.SksTopic;
import com.angeleo.sks.db.pojo.SksTopicExample;
import org.apache.ibatis.annotations.Param;

public interface SksTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    long countByExample(SksTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    int deleteByExample(SksTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    int insert(SksTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    int insertSelective(SksTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    SksTopic selectOneByExample(SksTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    SksTopic selectOneByExampleSelective(@Param("example") SksTopicExample example, @Param("selective") SksTopic.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    SksTopic selectOneByExampleWithBLOBs(SksTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    List<SksTopic> selectByExampleSelective(@Param("example") SksTopicExample example, @Param("selective") SksTopic.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    List<SksTopic> selectByExampleWithBLOBs(SksTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    List<SksTopic> selectByExample(SksTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    SksTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SksTopic.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    SksTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    SksTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SksTopic record, @Param("example") SksTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") SksTopic record, @Param("example") SksTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SksTopic record, @Param("example") SksTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SksTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SksTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SksTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") SksTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sks_topic
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}